package lmdelivery.longmen.com.android.util;

/**
 * Created by rufuszhu on 15-09-07.
 */
import java.util.Map;
import java.util.TreeMap;


public class CountryCode {

    final static Map<String, String> countryMap;

    static{
        //use tree map here in order to ignore case
        countryMap = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);
        countryMap.put("Andorra, Principality Of", "AD");
        countryMap.put("United Arab Emirates", "AE");
        countryMap.put("Afghanistan, Islamic State Of", "AF");
        countryMap.put("Antigua And Barbuda", "AG");
        countryMap.put("Anguilla", "AI");
        countryMap.put("Albania", "AL");
        countryMap.put("Armenia", "AM");
        countryMap.put("Netherlands Antilles", "AN");
        countryMap.put("Angola", "AO");
        countryMap.put("Antarctica", "AQ");
        countryMap.put("Argentina", "AR");
        countryMap.put("American Samoa", "AS");
        countryMap.put("Austria", "AT");
        countryMap.put("Australia", "AU");
        countryMap.put("Aruba", "AW");
        countryMap.put("Azerbaidjan", "AZ");
        countryMap.put("Bosnia-Herzegovina", "BA");
        countryMap.put("Barbados", "BB");
        countryMap.put("Bangladesh", "BD");
        countryMap.put("Belgium", "BE");
        countryMap.put("Burkina Faso", "BF");
        countryMap.put("Bulgaria", "BG");
        countryMap.put("Bahrain", "BH");
        countryMap.put("Burundi", "BI");
        countryMap.put("Benin", "BJ");
        countryMap.put("Bermuda", "BM");
        countryMap.put("Brunei Darussalam", "BN");
        countryMap.put("Bolivia", "BO");
        countryMap.put("Brazil", "BR");
        countryMap.put("Bahamas", "BS");
        countryMap.put("Bhutan", "BT");
        countryMap.put("Bouvet Island", "BV");
        countryMap.put("Botswana", "BW");
        countryMap.put("Belarus", "BY");
        countryMap.put("Belize", "BZ");
        countryMap.put("Canada", "CA");
        countryMap.put("Cocos (Keeling) Islands", "CC");
        countryMap.put("Central African Republic", "CF");
        countryMap.put("Congo, The Democratic Republic Of The", "CD");
        countryMap.put("Congo", "CG");
        countryMap.put("Switzerland", "CH");
        countryMap.put("Ivory Coast (Cote D'Ivoire)", "CI");
        countryMap.put("Cook Islands", "CK");
        countryMap.put("Chile", "CL");
        countryMap.put("Cameroon", "CM");
        countryMap.put("China", "CN");
        countryMap.put("Colombia", "CO");
        countryMap.put("Costa Rica", "CR");
        countryMap.put("Former Czechoslovakia", "CS");
        countryMap.put("Cuba", "CU");
        countryMap.put("Cape Verde", "CV");
        countryMap.put("Christmas Island", "CX");
        countryMap.put("Cyprus", "CY");
        countryMap.put("Czech Republic", "CZ");
        countryMap.put("Germany", "DE");
        countryMap.put("Djibouti", "DJ");
        countryMap.put("Denmark", "DK");
        countryMap.put("Dominica", "DM");
        countryMap.put("Dominican Republic", "DO");
        countryMap.put("Algeria", "DZ");
        countryMap.put("Ecuador", "EC");
        countryMap.put("Estonia", "EE");
        countryMap.put("Egypt", "EG");
        countryMap.put("Western Sahara", "EH");
        countryMap.put("Eritrea", "ER");
        countryMap.put("Spain", "ES");
        countryMap.put("Ethiopia", "ET");
        countryMap.put("Finland", "FI");
        countryMap.put("Fiji", "FJ");
        countryMap.put("Falkland Islands", "FK");
        countryMap.put("Micronesia", "FM");
        countryMap.put("Faroe Islands", "FO");
        countryMap.put("France", "FR");
        countryMap.put("France (European Territory)", "FX");
        countryMap.put("Gabon", "GA");
        countryMap.put("Great Britain", "UK");
        countryMap.put("Grenada", "GD");
        countryMap.put("Georgia", "GE");
        countryMap.put("French Guyana", "GF");
        countryMap.put("Ghana", "GH");
        countryMap.put("Gibraltar", "GI");
        countryMap.put("Greenland", "GL");
        countryMap.put("Gambia", "GM");
        countryMap.put("Guinea", "GN");
        countryMap.put("Guadeloupe (French)", "GP");
        countryMap.put("Equatorial Guinea", "GQ");
        countryMap.put("Greece", "GR");
        countryMap.put("S. Georgia & S. Sandwich Isls.", "GS");
        countryMap.put("Guatemala", "GT");
        countryMap.put("Guam (USA)", "GU");
        countryMap.put("Guinea Bissau", "GW");
        countryMap.put("Guyana", "GY");
        countryMap.put("Hong Kong", "HK");
        countryMap.put("Heard And McDonald Islands", "HM");
        countryMap.put("Honduras", "HN");
        countryMap.put("Croatia", "HR");
        countryMap.put("Haiti", "HT");
        countryMap.put("Hungary", "HU");
        countryMap.put("Indonesia", "ID");
        countryMap.put("Ireland", "IE");
        countryMap.put("Israel", "IL");
        countryMap.put("India", "IN");
        countryMap.put("British Indian Ocean Territory", "IO");
        countryMap.put("Iraq", "IQ");
        countryMap.put("Iran", "IR");
        countryMap.put("Iceland", "IS");
        countryMap.put("Italy", "IT");
        countryMap.put("Jamaica", "JM");
        countryMap.put("Jordan", "JO");
        countryMap.put("Japan", "JP");
        countryMap.put("Kenya", "KE");
        countryMap.put("Kyrgyz Republic (Kyrgyzstan)", "KG");
        countryMap.put("Cambodia, Kingdom Of", "KH");
        countryMap.put("Kiribati", "KI");
        countryMap.put("Comoros", "KM");
        countryMap.put("Saint Kitts & Nevis Anguilla", "KN");
        countryMap.put("North Korea", "KP");
        countryMap.put("South Korea", "KR");
        countryMap.put("Kuwait", "KW");
        countryMap.put("Cayman Islands", "KY");
        countryMap.put("Kazakhstan", "KZ");
        countryMap.put("Laos", "LA");
        countryMap.put("Lebanon", "LB");
        countryMap.put("Saint Lucia", "LC");
        countryMap.put("Liechtenstein", "LI");
        countryMap.put("Sri Lanka", "LK");
        countryMap.put("Liberia", "LR");
        countryMap.put("Lesotho", "LS");
        countryMap.put("Lithuania", "LT");
        countryMap.put("Luxembourg", "LU");
        countryMap.put("Latvia", "LV");
        countryMap.put("Libya", "LY");
        countryMap.put("Morocco", "MA");
        countryMap.put("Monaco", "MC");
        countryMap.put("Moldavia", "MD");
        countryMap.put("Madagascar", "MG");
        countryMap.put("Marshall Islands", "MH");
        countryMap.put("Macedonia", "MK");
        countryMap.put("Mali", "ML");
        countryMap.put("Myanmar", "MM");
        countryMap.put("Mongolia", "MN");
        countryMap.put("Macau", "MO");
        countryMap.put("Northern Mariana Islands", "MP");
        countryMap.put("Martinique (French)", "MQ");
        countryMap.put("Mauritania", "MR");
        countryMap.put("Montserrat", "MS");
        countryMap.put("Malta", "MT");
        countryMap.put("Mauritius", "MU");
        countryMap.put("Maldives", "MV");
        countryMap.put("Malawi", "MW");
        countryMap.put("Mexico", "MX");
        countryMap.put("Malaysia", "MY");
        countryMap.put("Mozambique", "MZ");
        countryMap.put("Namibia", "NA");
        countryMap.put("New Caledonia (French)", "NC");
        countryMap.put("Niger", "NE");
        countryMap.put("Norfolk Island", "NF");
        countryMap.put("Nigeria", "NG");
        countryMap.put("Nicaragua", "NI");
        countryMap.put("Netherlands", "NL");
        countryMap.put("Norway", "NO");
        countryMap.put("Nepal", "NP");
        countryMap.put("Nauru", "NR");
        countryMap.put("Neutral Zone", "NT");
        countryMap.put("Niue", "NU");
        countryMap.put("New Zealand", "NZ");
        countryMap.put("Oman", "OM");
        countryMap.put("Panama", "PA");
        countryMap.put("Peru", "PE");
        countryMap.put("Polynesia (French)", "PF");
        countryMap.put("Papua New Guinea", "PG");
        countryMap.put("Philippines", "PH");
        countryMap.put("Pakistan", "PK");
        countryMap.put("Poland", "PL");
        countryMap.put("Saint Pierre And Miquelon", "PM");
        countryMap.put("Pitcairn Island", "PN");
        countryMap.put("Puerto Rico", "PR");
        countryMap.put("Portugal", "PT");
        countryMap.put("Palau", "PW");
        countryMap.put("Paraguay", "PY");
        countryMap.put("Qatar", "QA");
        countryMap.put("Reunion (French)", "RE");
        countryMap.put("Romania", "RO");
        countryMap.put("Russian Federation", "RU");
        countryMap.put("Rwanda", "RW");
        countryMap.put("Saudi Arabia", "SA");
        countryMap.put("Solomon Islands", "SB");
        countryMap.put("Seychelles", "SC");
        countryMap.put("Sudan", "SD");
        countryMap.put("Sweden", "SE");
        countryMap.put("Singapore", "SG");
        countryMap.put("Saint Helena", "SH");
        countryMap.put("Slovenia", "SI");
        countryMap.put("Svalbard And Jan Mayen Islands", "SJ");
        countryMap.put("Slovak Republic", "SK");
        countryMap.put("Sierra Leone", "SL");
        countryMap.put("San Marino", "SM");
        countryMap.put("Senegal", "SN");
        countryMap.put("Somalia", "SO");
        countryMap.put("Suriname", "SR");
        countryMap.put("Saint Tome (Sao Tome) And Principe", "ST");
        countryMap.put("Former USSR", "SU");
        countryMap.put("El Salvador", "SV");
        countryMap.put("Syria", "SY");
        countryMap.put("Swaziland", "SZ");
        countryMap.put("Turks And Caicos Islands", "TC");
        countryMap.put("Chad", "TD");
        countryMap.put("French Southern Territories", "TF");
        countryMap.put("Togo", "TG");
        countryMap.put("Thailand", "TH");
        countryMap.put("Tadjikistan", "TJ");
        countryMap.put("Tokelau", "TK");
        countryMap.put("Turkmenistan", "TM");
        countryMap.put("Tunisia", "TN");
        countryMap.put("Tonga", "TO");
        countryMap.put("East Timor", "TP");
        countryMap.put("Turkey", "TR");
        countryMap.put("Trinidad And Tobago", "TT");
        countryMap.put("Tuvalu", "TV");
        countryMap.put("Taiwan", "TW");
        countryMap.put("Tanzania", "TZ");
        countryMap.put("Ukraine", "UA");
        countryMap.put("Uganda", "UG");
        countryMap.put("United Kingdom", "UK");
        countryMap.put("USA Minor Outlying Islands", "UM");
        countryMap.put("United States", "US");
        countryMap.put("Uruguay", "UY");
        countryMap.put("Uzbekistan", "UZ");
        countryMap.put("Holy See (Vatican City State)", "VA");
        countryMap.put("Saint Vincent & Grenadines", "VC");
        countryMap.put("Venezuela", "VE");
        countryMap.put("Virgin Islands (British)", "VG");
        countryMap.put("Virgin Islands (USA)", "VI");
        countryMap.put("Vietnam", "VN");
        countryMap.put("Vanuatu", "VU");
        countryMap.put("Wallis And Futuna Islands", "WF");
        countryMap.put("Samoa", "WS");
        countryMap.put("Yemen", "YE");
        countryMap.put("Mayotte", "YT");
        countryMap.put("Yugoslavia", "YU");
        countryMap.put("South Africa", "ZA");
        countryMap.put("Zambia", "ZM");
        countryMap.put("Zaire", "ZR");
        countryMap.put("Zimbabwe", "ZW");
    }

    public static final Map<String, String> codeMap;
    static{
        //use tree map here in order to ignore case
        codeMap = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);
        codeMap.put("AF", "Afghanistan");
        codeMap.put("AL", "Albania");
        codeMap.put("DZ", "Algeria");
        codeMap.put("AS", "American Samoa");
        codeMap.put("AD", "Andorra");
        codeMap.put("AO", "Angola");
        codeMap.put("AI", "Anguilla ");
        codeMap.put("AQ", "Antarctica");
        codeMap.put("AG", "Antigua and Barbuda");
        codeMap.put("AR", "Argentina");
        codeMap.put("AM", "Armenia");
        codeMap.put("AW", "Aruba");
        codeMap.put("AU", "Australia");
        codeMap.put("AT", "Austria");
        codeMap.put("AZ", "Azerbaijan");
        codeMap.put("BS", "Bahamas");
        codeMap.put("BH", "Bahrain");
        codeMap.put("BD", "Bangladesh");
        codeMap.put("BB", "Barbados");
        codeMap.put("BY", "Belarus");
        codeMap.put("BE", "Belgium");
        codeMap.put("BZ", "Belize");
        codeMap.put("BJ", "Benin");
        codeMap.put("BM", "Bermuda");
        codeMap.put("BT", "Bhutan");
        codeMap.put("BO", "'Bolivia, Plurinational State Of'  ");
        codeMap.put("BQ", "'Bonaire, Saint Eustatius and Saba'");
        codeMap.put("BA", "Bosnia and Herzegovina");
        codeMap.put("BW", "Botswana");
        codeMap.put("BV", "Bouvet Island");
        codeMap.put("BR", "Brazil");
        codeMap.put("IO", "British Indian Ocean Territory");
        codeMap.put("BN", "Brunei Darussalam");
        codeMap.put("BG", "Bulgaria");
        codeMap.put("BF", "Burkina Faso");
        codeMap.put("BI", "Burundi");
        codeMap.put("KH", "Cambodia");
        codeMap.put("CM", "Cameroon");
        codeMap.put("CA", "Canada");
        codeMap.put("CV", "Cape Verde  ");
        codeMap.put("KY", "Cayman Islands");
        codeMap.put("CF", "Central African Republic");
        codeMap.put("TD", "Chad");
        codeMap.put("CL", "Chile");
        codeMap.put("CN", "China");
        codeMap.put("CX", "Christmas Island");
        codeMap.put("CC", "Cocos (Keeling) Islands");
        codeMap.put("CO", "Colombia");
        codeMap.put("KM", "Comoros");
        codeMap.put("CG", "Congo");
        codeMap.put("CD", "'Congo, The Democratic Republic Of The'");
        codeMap.put("CK", "Cook Islands");
        codeMap.put("CR", "Costa Rica");
        codeMap.put("HR", "Croatia");
        codeMap.put("CU", "Cuba");
        codeMap.put("CW", "Curaçao");
        codeMap.put("CY", "Cyprus");
        codeMap.put("CZ", "Czech Republic");
        codeMap.put("CI", "Côte D\'Ivoire");
        codeMap.put("DK", "Denmark");
        codeMap.put("DJ", "Djibouti");
        codeMap.put("DM", "Dominica");
        codeMap.put("DO", "Dominican Republic");
        codeMap.put("EC", "Ecuador");
        codeMap.put("EG", "Egypt");
        codeMap.put("SV", "El Salvador");
        codeMap.put("GQ", "Equatorial Guinea");
        codeMap.put("ER", "Eritrea");
        codeMap.put("EE", "Estonia");
        codeMap.put("ET", "Ethiopia");
        codeMap.put("FK", "Falkland Islands  (Malvinas)");
        codeMap.put("FO", "Faroe Islands");
        codeMap.put("FJ", "Fiji");
        codeMap.put("FI", "Finland");
        codeMap.put("FR", "France");
        codeMap.put("GF", "French Guiana");
        codeMap.put("PF", "French Polynesia");
        codeMap.put("TF", "French Southern Territories");
        codeMap.put("GA", "Gabon");
        codeMap.put("GM", "Gambia");
        codeMap.put("GE", "Georgia");
        codeMap.put("DE", "Germany");
        codeMap.put("GH", "Ghana ");
        codeMap.put("GI", "Gibraltar");
        codeMap.put("GR", "Greece");
        codeMap.put("GL", "Greenland");
        codeMap.put("GD", "Grenada");
        codeMap.put("GP", "Guadeloupe");
        codeMap.put("GU", "Guam");
        codeMap.put("GT", "Guatemala");
        codeMap.put("GG", "Guernsey");
        codeMap.put("GN", "Guinea");
        codeMap.put("GW", "Guinea-Bissau");
        codeMap.put("GY", "Guyana");
        codeMap.put("HT", "Haiti");
        codeMap.put("HM", "Heard and McDonald Islands");
        codeMap.put("VA", "Holy See (Vatican City State)");
        codeMap.put("HN", "Honduras");
        codeMap.put("HK", "Hong Kong");
        codeMap.put("HU", "Hungary");
        codeMap.put("IS", "Iceland");
        codeMap.put("IN", "India");
        codeMap.put("ID", "Indonesia");
        codeMap.put("IR", "'Iran, Islamic Republic Of'");
        codeMap.put("IQ", "Iraq");
        codeMap.put("IE", "Ireland");
        codeMap.put("IM", "Isle of Man");
        codeMap.put("IL", "Israel");
        codeMap.put("IT", "Italy");
        codeMap.put("JM", "Jamaica");
        codeMap.put("JP", "Japan");
        codeMap.put("JE", "Jersey");
        codeMap.put("JO", "Jordan");
        codeMap.put("KZ", "Kazakhstan");
        codeMap.put("KE", "Kenya");
        codeMap.put("KI", "Kiribati");
        codeMap.put("KP", "'Korea, Democratic People\'s Republic Of'");
        codeMap.put("KR", "'Korea, Republic of'");
        codeMap.put("KW", "Kuwait");
        codeMap.put("KG", "Kyrgyzstan");
        codeMap.put("LA", "Lao People\'s Democratic Republic");
        codeMap.put("LV", "Latvia");
        codeMap.put("LB", "Lebanon");
        codeMap.put("LS", "Lesotho");
        codeMap.put("LR", "Liberia");
        codeMap.put("LY", "Libyan Arab Jamahiriya");
        codeMap.put("LI", "Liechtenstein");
        codeMap.put("LT", "Lithuania");
        codeMap.put("LU", "Luxembourg");
        codeMap.put("MO", "Macao");
        codeMap.put("MK", "'Macedonia, the Former Yugoslav Republic Of'");
        codeMap.put("MG", "Madagascar");
        codeMap.put("MW", "Malawi");
        codeMap.put("MY", "Malaysia");
        codeMap.put("MV", "Maldives");
        codeMap.put("ML", "Mali");
        codeMap.put("MT", "Malta");
        codeMap.put("MH", "Marshall Islands");
        codeMap.put("MQ", "Martinique");
        codeMap.put("MR", "Mauritania");
        codeMap.put("MU", "Mauritius");
        codeMap.put("YT", "Mayotte");
        codeMap.put("MX", "Mexico");
        codeMap.put("FM", "'Micronesia, Federated States Of'");
        codeMap.put("MD", "'Moldova, Republic of'");
        codeMap.put("MC", "Monaco");
        codeMap.put("MN", "Mongolia");
        codeMap.put("ME", "Montenegro");
        codeMap.put("MS", "Montserrat");
        codeMap.put("MA", "Morocco");
        codeMap.put("MZ", "Mozambique");
        codeMap.put("MM", "Myanmar");
        codeMap.put("NA", "Namibia");
        codeMap.put("NR", "Nauru");
        codeMap.put("NP", "Nepal");
        codeMap.put("NL", "Netherlands");
        codeMap.put("AN", "Netherlands Antilles");
        codeMap.put("NC", "New Caledonia");
        codeMap.put("NZ", "New Zealand");
        codeMap.put("NI", "Nicaragua");
        codeMap.put("NE", "Niger");
        codeMap.put("NG", "Nigeria");
        codeMap.put("NU", "Niue");
        codeMap.put("NF", "Norfolk Island");
        codeMap.put("MP", "Northern Mariana Islands");
        codeMap.put("NO", "Norway");
        codeMap.put("OM", "Oman");
        codeMap.put("PK", "Pakistan");
        codeMap.put("PW", "Palau");
        codeMap.put("PS", "'Palestinian Territory, Occupied'");
        codeMap.put("PA", "Panama");
        codeMap.put("PG", "Papua New Guinea");
        codeMap.put("PY", "Paraguay");
        codeMap.put("PE", "Peru");
        codeMap.put("PH", "Philippines");
        codeMap.put("PN", "Pitcairn");
        codeMap.put("PL", "Poland");
        codeMap.put("PT", "Portugal");
        codeMap.put("PR", "Puerto Rico");
        codeMap.put("QA", "Qatar");
        codeMap.put("RO", "Romania");
        codeMap.put("RU", "Russian Federation");
        codeMap.put("RW", "Rwanda");
        codeMap.put("RE", "Réunion");
        codeMap.put("BL", "Saint Barthélemy");
        codeMap.put("SH", "'Saint Helena, Ascension and Tristan Da Cunha'");
        codeMap.put("KN", "Saint Kitts And Nevis");
        codeMap.put("LC", "Saint Lucia");
        codeMap.put("MF", "Saint Martin");
        codeMap.put("PM", "Saint Pierre And Miquelon");
        codeMap.put("VC", "Saint Vincent And The Grenedines");
        codeMap.put("WS", "Samoa");
        codeMap.put("SM", "San Marino");
        codeMap.put("ST", "Sao Tome and Principe");
        codeMap.put("SA", "Saudi Arabia");
        codeMap.put("SN", "Senegal");
        codeMap.put("RS", "Serbia");
        codeMap.put("SC", "Seychelles");
        codeMap.put("SL", "Sierra Leone");
        codeMap.put("SG", "Singapore");
        codeMap.put("SX", "Sint Maarten (Dutch part)");
        codeMap.put("SK", "Slovakia");
        codeMap.put("SI", "Slovenia");
        codeMap.put("SB", "Solomon Islands");
        codeMap.put("SO", "Somalia");
        codeMap.put("ZA", "South Africa");
        codeMap.put("GS", "South Georgia and the South Sandwich Islands");
        codeMap.put("ES", "Spain");
        codeMap.put("LK", "Sri Lanka");
        codeMap.put("SD", "Sudan");
        codeMap.put("SR", "Suriname");
        codeMap.put("SJ", "Svalbard And Jan Mayen");
        codeMap.put("SZ", "Swaziland");
        codeMap.put("SE", "Sweden");
        codeMap.put("CH", "Switzerland");
        codeMap.put("SY", "Syrian Arab Republic  ");
        codeMap.put("TW", "'Taiwan, Province Of China'");
        codeMap.put("TJ", "Tajikistan");
        codeMap.put("TZ", "'Tanzania, United Republic of'");
        codeMap.put("TH", "Thailand");
        codeMap.put("TL", "Timor-Leste");
        codeMap.put("TG", "Togo");
        codeMap.put("TK", "Tokelau");
        codeMap.put("TO", "Tonga");
        codeMap.put("TT", "Trinidad and Tobago");
        codeMap.put("TN", "Tunisia");
        codeMap.put("TR", "Turkey");
        codeMap.put("TM", "Turkmenistan");
        codeMap.put("TC", "Turks and Caicos Islands");
        codeMap.put("TV", "Tuvalu");
        codeMap.put("UG", "Uganda");
        codeMap.put("UA", "Ukraine");
        codeMap.put("AE", "United Arab Emirates");
        codeMap.put("GB", "United Kingdom");
        codeMap.put("US", "United States");
        codeMap.put("UM", "United States Minor Outlying Islands");
        codeMap.put("UY", "Uruguay");
        codeMap.put("UZ", "Uzbekistan");
        codeMap.put("VU", "Vanuatu");
        codeMap.put("VE", "'Venezuela, Bolivarian Republic of' ");
        codeMap.put("VN", "Viet Nam");
        codeMap.put("VG", "'Virgin Islands, British'");
        codeMap.put("VI", "'Virgin Islands, U.S.'");
        codeMap.put("WF", "Wallis and Futuna");
        codeMap.put("EH", "Western Sahara");
        codeMap.put("YE", "Yemen");
        codeMap.put("ZM", "Zambia");
        codeMap.put("ZW", "Zimbabwe");
        codeMap.put("AX", "Åland Islands");
    }

    public static String getCode(String country){
        return countryMap.get(country);
    }
    public static String getCountryName(String code){
        return codeMap.get(code);
    }
}